[[redirects]]
  from = "/api/.netlify/functions/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/.netlify/functions/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/.netlify/functions/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/.netlify/functions/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 200
  force = false
