[[redirects]]
  from = "/api/.netlify/functions/users"
  to = "/.netlify/functions/users/users.js"
  status = 200

[[redirects]]
  from = "/api/.netlify/functions/register"
  to = "/.netlify/functions/register/register.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 200
  force = false
