[[redirects]]
  from = "/api/register"
  to = "/api/register.js"
  status = 200
[[redirects]]
  from = "/api/test"
  to = "/api/test.js"
  status = 200
[[redirects]]
  from = "/api/users"
  to = "/api/users.js"
  status = 200
[[redirects]]
  from = "/*"
  to = "/src/index.html"
  status = 200
  force = false